### ISSUE TITLE
Add extension to Open VSX registry

### ISSUE THREAD

**Issue by sbstn87** [felipemullen/tldr-panel#1]
Hi,

can you add your extension to Open VSX registry?

https://open-vsx.org/

It will make it available to other than official builds of VSCode, like VSCodium.

**Comment by felipemullen** [comment]
Sure, looks like it shouldn't be too much work

**Comment by felipemullen** [comment]
Hi @sbstn87 I have published the extension, it is now available here:
https://open-vsx.org/extension/felipemullen/tldr-panel

I hope it works well for you, let me know if you encounter issues
